import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";
import RegisterModal from "./components/modals/RegisterModal";
import ReactQueryProvider from "./components/providers/ReactQueryProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "@/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  console.log(currentUser);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <Navbar currentUser={currentUser} />
          <RegisterModal />
          <LoginModal />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
